const lines = [
  "# Runner Help",
  "",
  "Primary chain:",
  "1. npm run runner:goal -- --roles <roles> \"request\"",
  "   Safe rehearsal. Applies, verifies, rolls back, then reports.",
  "2. npm run runner:latest:status",
  "   Inspect the latest run and continue-chain commands.",
  "3. npm run runner:latest:b",
  "   Preview keeping the latest proposed edits.",
  "4. npm run runner:latest:b:execute",
  "   Keep the latest proposed edits intentionally.",
  "",
  "When you already have a run id:",
  "- npm run runner:status -- <run-id>",
  "- npm run runner:continue:a -- <run-id>",
  "- npm run runner:continue:b -- <run-id>",
  "- npm run runner:continue:b:execute -- <run-id>",
  "- npm run runner:continue:c -- <run-id>",
  "",
  "Low-cost checks:",
  "- npm run runner:goal:budget -- --roles frontend \"request\"",
  "- npm run runner:plan:budget -- --roles frontend \"request\"",
  "- npm run runner:goal:mock -- --roles frontend,java \"request\"",
  "- npm run runner:plan:mock -- --roles frontend,java \"request\"",
  "- npm run ci:dry-run",
  "",
  "Safety notes:",
  "- runner:goal is a rollback rehearsal; it does not keep edits.",
  "- runner:goal:budget stops when estimated API cost exceeds $0.10.",
  "- runner:plan:budget stops when estimated API cost exceeds $0.05.",
  "- Option B execute keeps edits. Use it only after reviewing the report.",
  "- Option C is preview-only because it means reject/replan.",
];

console.log(lines.join("\n"));
